## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'horiba'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_horiba' #to modify
description = 'Set of PyMoDAQ plugins for Horiba Instruments (Lapspec6TCP to communicate with labspec softaware using the AFM TCP/IP protocol)'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = []
##